unique_ids:
  assets:
    nb.png: FO5QPHUSWEKVDUBRQMG6IX6Y7P46FPVY
    standard-page.html: 2MRJYJEMZW6VA4HKBOVARSIXTDI7GKYS
    theme.css: 527UXK2FZRN42XK2CE4PLZ3ZQ6F672YV
  forms:
    Lable: '1755065285358196354578612.5448'
    Splashform: GBJL3543LAXP334KEVXDRCBBNZZ6KXJM
  modules: {}
  scripts: {}
  server_modules: {}
