unique_ids:
  assets:
    nb.png: '1755036279987552733547609.1064'
    standard-page.html: 2MRJYJEMZW6VA4HKBOVARSIXTDI7GKYS
    theme.css: 527UXK2FZRN42XK2CE4PLZ3ZQ6F672YV
  forms:
    Splashform: '1755035945416499105466885.3785'
    splashform: OKGNBBBQ6JK2H6SUMLTR3NCBJTS7BZVN
  modules: {}
  scripts: {}
  server_modules: {}
